apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-grafana-datasource
  namespace: observability
  labels:
    grafana_datasource: "1"

data:
  tempo.yaml: |
    apiVersion: 1

    datasources:
      - name: Tempo
        uid: tempo
        type: tempo
        access: proxy
        url: http://tempo.tempo.svc.cluster.local:3200
        editable: false
