alertmanager:
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: discord
      group_by:
        - alertname
        - namespace
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h

      routes:
        - receiver: 'null'
          matchers:
            - 'alertname="Watchdog"'

    receivers:
      - name: 'null'

      - name: discord
        discord_configs:
          - webhook_url_file: /etc/alertmanager/secrets/discord-webhook/webhook-url
            send_resolved: true

  alertmanagerSpec:
    secrets:
      - discord-webhook
