apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-discord-test
  namespace: observability
  labels:
    release: sre-monitoring
spec:
  groups:
    - name: sre.discord.test
      rules:
        - alert: SREDiscordTest
          expr: vector(1)
          for: 0m
          labels:
            severity: warning
          annotations:
            summary: "Prometheus to Discord test"
            description: "Prometheus -> Alertmanager -> Discord is working."
